name: Deploy Vite site via FTP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy extra root files into dist/
        run: |
          cp sitemap.xml dist/
          cp manifest.json dist/
          cp .htaccess dist/

      - name: Inject TURNSTILE_SECRET into contact.php
        run: |
          sed "s|{{TURNSTILE_SECRET}}|${{ secrets.TURNSTILE_SECRET }}|g" contact.php > dist/contact.php

      - name: Deploy via FTP with lftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.amld.es
          username: amldes2022
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
          timeout: 60000